### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by ThermScissorpunch** [ripe-tech/ups-api-js#27]
Is is possible to add documentation on how to simply use this plugin?
It would help a lot :-)

**Comment by joao-conde** [comment]
Hey @ThermScissorpunch 

I appreciate the time you took to raise awareness about the lack of example usage of this package.

Are you having trouble using this package in your javascript projects? If so, I can provide some help. But if you already know how to use it, I encourage you to open a pull request to improve the documentation.

Furthermore, are you having trouble instantiating the API client and calling a method? Or do you find the documentation regarding each method parameter to be lacking and therefore you do not know what properties to pass?

Let me know if [this PR](https://github.com/ripe-tech/ups-api-js/pull/28) solves your issues.

**Comment by joao-conde** [comment]
@ThermScissorpunch pinging you on this matter, otherwise closing it in a few days.
