### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by fearganni** [ripe-tech/ups-api-js#35]
Would be amazing if you could  add typescript support, was trying to do it myself but I am not used to the file formatting going on 🙏

**Comment by joao-conde** [comment]
Hello @fearganni ,

Sorry for the delay. Thank you for opening this issue.

Are we talking about adding a typical "types" package to this repository? I think this could work great for parameter documentation as well.

If so, maybe you could contribute it? Maybe I can help you with any questions.

**Comment by fearganni** [comment]
Hey @joao-conde, thanks so much for your reply! 
I am honestly not too familiar with creating type definitions for modules.

Maybe https://github.com/DefinitelyTyped/DefinitelyTyped can help?

**Comment by joao-conde** [comment]
We could do something similar to: https://github.com/ripe-tech/ripe-sdk/tree/master/types

I guess what I was asking is, do you want to take a shot at it? Currently I cant provide an estimation or a guarantee we will have time to tackle this.

**Comment by laurensiusadi** [comment]
I think this will be a help https://github.com/Babbiorsetto/ups-typescript-fetch-client

**Comment by joao-conde** [comment]
@fearganni  The company no longer maintains this or focus on this product at all. Its a shame because that TS client is very nice, thanks for sharing.

**Comment by fearganni** [comment]
> @fearganni The company no longer maintains this or focus on this product at all. Its a shame because that TS client is very nice, thanks for sharing.

Understandable, I am sure there's more updated alternatives out there now anyways.
